openapi: "3.0.2"
info:
  title: "RSS-Server"
  description: "This is simple REST API for CRUD requests with rss links."
  version: "1.0.0"
  contact:
    name: "Dmitry Kutuzov"
    email: "archie-defis-woc@ya.ru"

paths:
  /users/register:
    post:
      summary: 'Register new user'
      description: 'Register new user and return UserModel'
      requestBody:
        description: 'User registration body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterDto'
      responses:
        '200':
          description: "User successfully registered"
          content:
            application/json:
              schema:
                type: object
                properties:
                  email: 
                    type: string
                  id: 
                    type: number
                example:
                  id: 1
                  email: "hahaha@ya.ru"
                
        '400':
          description: 'Validation error: invalid input request'
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/HttpErrorResponse'
        '422':
          description: 'User already exists'
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/HttpErrorResponse'
  /users/login:
    post:
      summary: 'Identificates user'
      description: 'Authorizates user by password'
      requestBody:
        description: 'User login body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDto'
      responses:
        '200':
          description: 'Succesfully authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
        '400':
          description: 'Validation error: invalid input request'
        '401':
          description: 'Authorization failed'
  /users/info:
    post:
      summary: 'Gets user information'
      description: 'Gets user informaion only for authorized user'
      security:
        - bearerAuth: []
          
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
              example:
                user: 'hahaha@ya.ru'
      responses:
        '200':
          description: 'Succesfully gets user information'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  name:
                    type: string
        '404':
          $ref: '#/components/responses/UnauthorizedError'
          
components:
  schemas:
    UserRegisterDto:
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    UserLoginDto:
      properties:
          email:
            type: string
          password:
            type: string
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  responses:
    UnauthorizedError:
      description: 'Access token is missing or invalid'
      
    # HttpErrorResponse:
    #   type: object
    #   properties:
    #     err:
    #       type: string
