name: INTSUM CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run generate
          npm run build
      - name: Test with linter
        run: |
          npm run lint
      - name: Migration
        env: 
          SALT: 5
          SECRET: "no-secrets"
          DATABASE_URL: "file:./dev.db"
        run: |
          npm run migrate
      - name: e2e test
        env: 
          SALT: 5
          SECRET: "no-secrets"
          DATABASE_URL: "file:./dev.db"
        run: |
          npm run test
